
message(STATUS "include Platform.cmake")

if(NOT RE_TARGET_PLATFORM)
	IF (WIN32)
		MESSAGE(STATUS "Current System WIN32")
		set(RE_TARGET_PLATFORM "Windows")
	ELSEIF (APPLE)
		MESSAGE(STATUS "Current System Apple")
		set(RE_TARGET_PLATFORM "MacOS")
	ELSEIF (UNIX)
		MESSAGE(STATUS "Current System Unix")
		set(RE_TARGET_PLATFORM "Linux")
	ENDIF ()
endif()

if(${RE_TARGET_PLATFORM} STREQUAL "Windows")
	set(IS_WINDOWS 1)
	include("${CMAKE_CURRENT_LIST_DIR}/Windows.cmake")
elseif(${RE_TARGET_PLATFORM} STREQUAL "MacOS")
	set(IS_MACOS 1)
	include("${CMAKE_CURRENT_LIST_DIR}/MacOS.cmake")
elseif(${RE_TARGET_PLATFORM} STREQUAL "Linux")
	set(IS_LINUX 1)
	include("${CMAKE_CURRENT_LIST_DIR}/Linux.cmake")
elseif(${RE_TARGET_PLATFORM} STREQUAL "iOS")
	set(IS_IOS 1)
	include("${CMAKE_CURRENT_LIST_DIR}/iOS.cmake")
elseif(${RE_TARGET_PLATFORM} STREQUAL "Android")
	set(IS_ANDROID 1)
	include("${CMAKE_CURRENT_LIST_DIR}/Android.cmake")
endif()

